### PR TITLE
feature/Guild Page for fast actions

### PR DESCRIPTION
**Pull request by saurfang**
Introduce Guild (name TBD) where user can manage all adventurers with fast actions. In the future, we can consider extending this with informatics like tables that provide a compact view and access to adventurers.

This a new standalone page under Town. It currently provides two functionalities:
- Send eligible adventurers to adventure with one click. The action will trigger one transaction for each adventurer. If no adventurer is eligible, the time to next earliest adventure is shown
- Claim gold for all adventurers with one click. The action will trigger one transaction for each adventurer. 

TO DO
- [x] Agree on the naming of the page
- [x] Find asset for the icon (do you use some stock assets?)

image

### CODE REVIEW

**Comment by TBouder** [comment]
Hey !
Thank you for this draft !
This could be a great thing to add !

We currently have two solutions to handle multi-actions (or more I may not be aware of):
- Having a smartcontract to handle that, but you first have to approve the smartcontract to do actions for your adventurer (we have this in our roadmap, but no implementation yet)
- Just looping through the adventurers and executing each transaction one by one

A nice addition would also be a `fast actions page` where you just have a list of all the possible actions for you.
You are welcome to contribute on that, this is a community game, and a community project :)
For the branch, I will update the `develop` branch with the current `develop` status, you can use this one to work on

**Comment by saurfang** [comment]
Thanks. I moved this to a new page tentatively called Guild but open to new name and copies. It implements the simple loop idea for going adventure and claiming gold. Let me know if there's anything else I can help to get this in.

By the way, do you have a discord or discord channel in the official Rarity discord to get in touch? Also, do you have a local auto-formatter config like prettier that you can share? My IDE really wants to format it a completely different way :)

**Comment by TBouder** [comment]
Hey !
Thank you for that!
I (or Facu) will check that later today :)

In the meantime, you can get in touch with me on Telegram `@Major_eth` !

**Comment by TBouder** [comment]
@saurfang could you remove the [WIP] once this is ready to review, and convert it to `Draft pull request` in the meantime ? Thank you !

**Comment by saurfang** [comment]
Thanks @TBouder. This is ready for review. I just need your input on two outstanding things.

**Comment by Ceazor** [comment]
This is a solid idea.

Perhaps.. Change "Guild" to "Guild House" as town is buildings.

and perhaps change 

Send 2 Adventurers to Adventures

to 

SEND YOUR WHOLE PARTY ON ADVENTURES

Just to remove the double words.

**Comment by saurfang** [comment]
Guild House makes a lot more sense! Thank you. I updated the icon. ptal? @TBouder 

I'll poke at automating rat fighting separately. I might also look into a compact UI to list adventurers in the guild house page.

**Comment by TBouder** [comment]
That's great IMO !

Just something to change later : When I send all my party to adventure, the message from Facu is `next adventure in 1 day`, and not the default message !

Thank you for that, I merge now !

**Review by TBouder — APPROVED** [review]

**Pull request merged**
