### PR TITLE
Feature/skills

### PR DESCRIPTION
**Pull request by TBouder**
## What it does ✨
Add the SkillBook and the Skills to Rarity Extended.
Skills are following  the logic of [this contract](https://ftmscan.com/address/0x51c0b29a1d84611373ba301706c6b4b72283c80f#code) explained on [this medium post](https://andrecronje.medium.com/rarity-skills-7dded308a607). Design was made by our well know designer and we are re-working the design system based on this PR !

You can now:
- See the skills of your adventurers
- Set some skills if you have available points
- Get the details of the skills
- Work with reponsive design

Capture d’écran 2021-09-16 à 12 19 48
Capture d’écran 2021-09-16 à 12 20 06
Capture d’écran 2021-09-16 à 12 21 12
Capture d’écran 2021-09-16 à 12 19 39

## How to test ✅
You should be able to set the skills for your adventurer without issue.

### CODE REVIEW

**Comment by Ceazor** [comment]
Add.. "Your Current Attributes" in the circle

image

**Comment by Ceazor** [comment]
Change Adventures to "Quests" or "Dungeons"

So players don't get confused between daily XP "adventures"
image

**Comment by saltyfacu** [comment]
**When I go into SKILLS, I select the skill and click "LEARN", MM opens, I confirm, nothing happens.**
Why? I need to change level 0 to level 1. 
LEARN button shouldn't be enabled if it's not possible to actually LEARN anything

**When I assign every point I have, back arrows disappear without clicking LEARN.**
This only happens when I assign points to a skill that I've already learned.
- I learn CONCENTRATION, so I have it with level 1
- I go to my skills and increase it's level until 5, I cannot decrease it any more

** I learned 2 skills and magically got 25.5 points **
Should I get half a point for some reason? How did I get those 25 points?

Check the screenshot

Screenshot 2021-09-16 at 12 43 28

 **Inventory is not according to figma**
- These two buttons are very different. We should use the "go to the quest office" button.
- It has a line separating the tab title from the body when Skills doesn't have it.

Screenshot 2021-09-16 at 12 47 14

**Comment by saltyfacu** [comment]
**Nice to have**: when I have only 1 point left, it'd be nice to remove the arrow from skills that cost 2 points, like what we do when all points are spent.

**Review by saltyfacu — APPROVED** [review]
awesome job! I love it. Just a "nice to have". Ship eet

**Pull request merged**
