### PR TITLE
Feature/Dungeon The Cellar & FTM Vault

### PR DESCRIPTION
**Pull request by TBouder**
## What it does ✨
Adding the first Dungeon `The Cellar` to Rarity Extended !
- [Medium article](https://andrecronje.medium.com/rarity-the-cellar-83a1606a0be3)
- [SmartContract](https://ftmscan.com/address/0x2a0f1cb17680161cf255348ddfdee94ea8ca196a#readContract)

Capture d’écran 2021-09-09 à 15 55 26

Moreover, this PR adds:
- Draft for the FTM vault on ape.tax to stake wftm
- Animation for Facu the tavern keeper
- Refactor the dialogs buttons
- Refactor the tavern UX
- Refactor the adventurer selector for an adventure

## How to test ✅
You can setup a fork of FTM and just try to interact with RE. This should correctly work.

## Note
Another PR to handle the items in a better way should be done

### CODE REVIEW

**Comment by fameal** [comment]
- When depositing FTM. In the end, there's a "?" missing.

- When I click deposit 75% (or others) just opens metamask. That's weird. What do you think about changing the text to something around: "GREAT CHOICE! LET'S PROCESS YOUR TRANSACTION" or something better.

- When I canceled the TX is showed me as if I confirmed. It should say something around "OH YOU CHANGED YOUR MIND!" maybe Ceazor can make it better

- The confirmation phrase has a few typos. Here's the fixed version:
THIS IS A GREAT INVESTMENT! TRUST ME! YOU CAN CLICK HERE TO CHECK YOUR INVESTMENT UNTIL THE BANK IS BUILT IN THIS HUMBLE TOWN!

**Comment by TBouder** [comment]
Contract used for the FTM vault -> https://ftmscan.com/address/0xea339e15519a6c939371efe596851f9c062f5e5f
Contract of the vault -> https://ftmscan.com/address/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0#code
Current ape.tax UI -> https://ape.tax/the-fantom
Source code for the Zap -> https://github.com/pandadefi/ftmzap

**Comment by fameal** [comment]
The test saying "you changed your mind" stays even after a successful deposit.

How to reproduce:
- Press deposit
- Cancel transaction
- Press deposit
- Accept transaction

**Review by fameal — APPROVED** [review]
LGTM! Great PR 🚀

**Pull request merged**
